Paso 1: Carga de datos y exploración inicial
El primer paso es importar las herramientas necesarias y leer el archivo de datos.

Código: Utiliza la librería pandas para cargar un archivo CSV llamado googleplaystore.csv en un objeto llamado "DataFrame" (una tabla virtual).

Explicación simple: Es como abrir un archivo de Excel dentro de Python para poder trabajar con él. El código también muestra las "dimensiones" (cuántas filas y columnas hay) y enseña las primeras 5 filas para verificar que todo se cargó bien.

In [7]:
#primero leemos la base de datos y la pasamos a un dataframe

import pandas as pd

df = pd.read_csv("/content/googleplaystore.csv")
print(f"Dimensiones: {df.shape}")
df.head(5)

Dimensiones: (10841, 13)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

Paso 2: Detección de duplicados
Antes de limpiar, es necesario saber cuánta información está repetida.

Código: Usa la función .duplicated().sum() para contar cuántas filas son exactamente iguales a otras.

Explicación simple: El programa busca registros que sean "copia fiel" de otros. Calcula qué porcentaje del total representan estos duplicados (en este caso, un 4.46%) y te muestra una pequeña muestra de ellos para que confirmes que realmente sobran.

In [10]:
import pandas as pd

# 1. Conteo total de filas duplicadas (exactas)
total_duplicados = df.duplicated().sum()
porcentaje_duplicados = (total_duplicados / len(df)) * 100

print(f"Total de registros idénticos duplicados: {total_duplicados}")
print(f"Representan el {porcentaje_duplicados:.2f}% del dataset.")

# 2. Visualización de los duplicados para inspección manual
# Esto ayuda a la "Justificación de decisiones" en la presentación
if total_duplicados > 0:
    print("\nMuestra de registros duplicados:")
    display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(4))

Total de registros idénticos duplicados: 483
Representan el 4.46% del dataset.

Muestra de registros duplicados:

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1393,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
1407,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
2322,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2543,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up

Paso 3: Creación de una función de limpieza
Para que el proceso sea profesional y reutilizable, el código define una "función" (una instrucción personalizada).

Código: Se crea la función eliminar_duplicados(df, columnas_clave=None).

Explicación simple: Esta función es como una herramienta automática a la que le pasas la tabla sucia y ella te devuelve la tabla limpia. Está programada para borrar las repeticiones y decirte exactamente cuántas filas eliminó.

In [11]:
def eliminar_duplicados(df, columnas_clave=None):
    try:
        antes = len(df)
        # Se mantiene la primera ocurrencia (keep='first')
        df_limpio = df.drop_duplicates(subset=columnas_clave, keep='first')
        despues = len(df_limpio)

        print(f"Registros eliminados: {antes - despues}")
        return df_limpio

    except KeyError as e:
        print(f"Error: Una de las columnas clave no existe: {e}")
        return df
    except Exception as e:
        print(f"Ocurrió un error inesperado: {e}")
        return df

Paso 4: Aplicación de la limpieza y verificación
Aquí es donde realmente se transforman los datos.

Código: Se aplica la función anterior y se crea un nuevo objeto llamado df_sin_duplicados.

Explicación simple: Se ejecuta el proceso de borrado. El resultado pasa de tener 10,841 registros a 10,358 registros únicos. Al final, se usa .info() para ver un resumen de las columnas y detectar si faltan datos (valores nulos) en categorías como "Rating" o "Android Ver".

In [12]:
# Aplicar la función
df_sin_duplicados = eliminar_duplicados(df)

# Verificación de integridad: ¿Quedaron nulos tras la operación?
nulos_post = df_sin_duplicados.isnull().sum().sum()

# Auditoría técnica (Checksum simple del tamaño)
print(f"Integridad verificada: Dataset final con {len(df_sin_duplicados)} registros únicos.")
print(f"Dimensiones: {df_sin_duplicados.shape}")

Registros eliminados: 483
Integridad verificada: Dataset final con 10358 registros únicos.
Dimensiones: (10358, 13)

In [13]:
df_sin_duplicados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

Paso 5: Estandarización y análisis de datos faltantes
En este punto, el código busca "agujeros" o información incompleta que pueda arruinar tus análisis futuros.

Código: Se crea una lista de símbolos sospechosos, se reemplazan por un valor vacío estándar (NaN) y se genera una tabla resumen con el conteo y porcentaje de nulos por columna.

Explicación simple: A veces los datos no están vacíos, sino que tienen símbolos como "?" o "-". El código los convierte todos en "vacíos oficiales" para que Python los reconozca. Luego, te muestra un informe tipo "ranking" con las columnas que tienen más errores, diciéndote qué tan grave es el problema (por ejemplo, si te falta el 1% o el 50% de los datos).

In [14]:
import pandas as pd
import numpy as np

# Reemplazar valores sospechosos por NaN de NumPy para que Pandas los reconozca
valores_a_reemplazar = ["?", "n/a", " ", "-", "None"]
df.replace(valores_a_reemplazar, np.nan, inplace=True)

# Resumen de nulos por columna
resumen_nulos = pd.DataFrame({
    'Nulos': df.isnull().sum(),
    'Porcentaje (%)': (df.isnull().sum() / len(df)) * 100,
    'Tipo de Dato': df.dtypes
})

# Mostrar solo las columnas que tienen nulos (ordenadas de mayor a menor)
print("Análisis de datos faltantes:")
print(resumen_nulos[resumen_nulos['Nulos'] > 0].sort_values(by='Nulos', ascending=False))

Análisis de datos faltantes:
                Nulos  Porcentaje (%) Tipo de Dato
Rating           1474       13.596532      float64
Current Ver         8        0.073794       object
Android Ver         3        0.027673       object
Content Rating      1        0.009224       object
Type                1        0.009224       object

Paso 6: Imputación avanzada y validación de integridad
En este paso, el código deja de solo "observar" los huecos y pasa a rellenarlos de forma inteligente para que el dataset esté completo y listo para el análisis.

Código: Se define una función profesional que separa las columnas en números y categorías. A los números les asigna la mediana y a las categorías la moda (el valor más frecuente), terminando con una auditoría para confirmar que ya no quedan nulos.

In [15]:
import pandas as pd
import numpy as np

def ejecutar_limpieza_nulos(df_input):
    """
    Realiza la limpieza de nulos aplicando técnicas de imputación avanzadas.
    Cumple con: Código limpio, documentado y manejo de excepciones.
    """
    try:
        # 1. Crear una copia para asegurar la reproducibilidad
        # Foco de observación: Organización y reproducibilidad [cite: 24]
        df_work = df_input.copy()

        # 2. Identificar columnas por tipo de dato
        # Uso de herramientas: Pandas y NumPy
        cols_num = df_work.select_dtypes(include=[np.number]).columns
        cols_cat = df_work.select_dtypes(include=['object', 'category']).columns

        print(f"--- Iniciando limpieza de {len(df_work)} registros ---")

        # 3. Imputación de variables Numéricas
        # Justificación técnica: La mediana es robusta frente a valores atípicos (outliers)
        for col in cols_num:
            if df_work[col].isnull().any():
                mediana = df_work[col].median()
                df_work[col] = df_work[col].fillna(mediana)
                print(f"Columna '{col}': Nulos imputados con mediana ({mediana})")

        # 4. Imputación de variables Categóricas
        # Justificación técnica: Se usa la moda para mantener la tendencia central de la categoría
        for col in cols_cat:
            if df_work[col].isnull().any():
                moda = df_work[col].mode()[0]
                df_work[col] = df_work[col].fillna(moda)
                print(f"Columna '{col}': Nulos imputados con moda ('{moda}')")

        # 5. Verificación de Integridad (Punto 6 de la Pauta)
        # Aplica técnicas de verificación de integridad y procedencia [cite: 81]
        nulos_finales = df_work.isnull().sum().sum()

        if nulos_finales == 0:
            print("\n✅ Validación Exitosa: El dataset no contiene valores nulos.")
        else:
            print(f"\n⚠️ Advertencia: Aún existen {nulos_finales} valores nulos.")

        return df_work

    except Exception as e:
        # Manejo de excepciones requerido por la pauta [cite: 48]
        print(f"❌ Error crítico durante la limpieza: {e}")
        return df_input

# --- EJECUCIÓN ---
# Reemplazamos y procesamos sobre la base sin duplicados
df_final = ejecutar_limpieza_nulos(df_sin_duplicados)

# Mostrar resumen final para el Informe Técnico [cite: 40]
print("\nResumen del Dataset Limpio:")
print(df_final.info())

--- Iniciando limpieza de 10358 registros ---
Columna 'Rating': Nulos imputados con mediana (4.3)
Columna 'Type': Nulos imputados con moda ('Free')
Columna 'Content Rating': Nulos imputados con moda ('Everyone')
Columna 'Current Ver': Nulos imputados con moda ('Varies with device')
Columna 'Android Ver': Nulos imputados con moda ('4.1 and up')

✅ Validación Exitosa: El dataset no contiene valores nulos.

Resumen del Dataset Limpio:
<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          10358 non-null  float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10358 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10358 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10358 non-null  object
 12  Android Ver     10358 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None

Paso 7: Verificación de integridad final y auditoría
Este es el último control de calidad. Aquí el código actúa como un inspector que revisa que todo el trabajo anterior se haya realizado correctamente antes de entregar los datos.

Código: Se crea una función de validación que genera un reporte con tres métricas clave: el total de valores nulos, el total de registros duplicados y el tamaño final de la tabla (filas y columnas).

In [16]:
# Verificación de integridad final
def validar_estado_final(df):
    reporte = {
        "Nulos totales": df.isnull().sum().sum(),
        "Duplicados totales": df.duplicated().sum(),
        "Dimensiones finales": df.shape
    }
    return reporte

# Ejecutar validación
estado = validar_estado_final(df_final)
print("\n--- Reporte de Integridad Final ---")
for k, v in estado.items():
    print(f"{k}: {v}")

--- Reporte de Integridad Final ---
Nulos totales: 0
Duplicados totales: 0
Dimensiones finales: (10358, 13)

Paso 8: Conversión de formatos y limpieza de caracteres especiales
En este paso, el código toma una columna que parece numérica pero que Python lee como "texto" (debido a símbolos como + o ,) y la transforma en números reales para poder sumar, promediar o comparar.

Código: Se crea una función que busca y elimina los símbolos de más (+) y las comas (,) de la columna "Installs". Luego, convierte esos textos en números enteros (int) y, si encuentra algún error o palabra extraña (como "Free"), la convierte en un 0 para no trabar el proceso.

In [17]:
def transformar_installs(df):
    try:
        df_temp = df.copy()
        # Eliminar '+' y ',' usando vectorización de pandas
        df_temp['Installs'] = df_temp['Installs'].str.replace('+', '', regex=False)
        df_temp['Installs'] = df_temp['Installs'].str.replace(',', '', regex=False)

        # Caso especial: Si existe algún valor no numérico (como 'Free' en filas corruptas)
        df_temp['Installs'] = pd.to_numeric(df_temp['Installs'], errors='coerce').fillna(0).astype(int)

        print("✅ Columna 'Installs' transformada a entero.")
        return df_temp
    except Exception as e:
        print(f"❌ Error en transformar_installs: {e}")
        return df

df_final = transformar_installs(df_final)

✅ Columna 'Installs' transformada a entero.

Paso 9: Limpieza de valores fuera de rango y normalización de unidades (Size)
En este paso, el código realiza una "cirugía" a los datos para corregir errores lógicos y unificar las unidades de medida del tamaño de las aplicaciones (pasando todo a Megabytes).

Código: Primero, elimina filas con errores absurdos (como un Rating de 19 cuando el máximo es 5). Luego, crea una función que detecta si el tamaño está en Kilobytes ('K') o Megabytes ('M'), hace la conversión matemática para que todo quede en MB y, finalmente, rellena los textos como "Varies with device" usando la mediana de la columna.

In [18]:
import pandas as pd
import numpy as np

# 1. LIMPIEZA PREVIA: Eliminar fila corrupta (esencial para que no afecte el promedio/mediana)
# En el dataset original, hay una fila donde el Rating es 19.0 (imposible).
df_final = df_final[df_final['Rating'] <= 5.0].copy()

def convertir_size_a_mb_final(valor):
    """
    Convierte el texto de Size a números flotantes en MB.
    Maneja 'M', 'k', 'Varies with device' y errores de formato.
    """
    if pd.isna(valor) or not isinstance(valor, str):
        return np.nan

    valor = valor.upper().strip()

    try:
        if 'M' in valor:
            return float(valor.replace('M', ''))
        elif 'K' in valor:
            # Dividimos por 1024 para pasar de KB a MB
            return float(valor.replace('K', '')) / 1024
        elif 'VARIES WITH DEVICE' in valor:
            return np.nan
        else:
            # Intenta convertir si es un número puro en string
            return pd.to_numeric(valor, errors='coerce')
    except:
        return np.nan

# 2. Aplicar la función de conversión
df_final['Size'] = df_final['Size'].apply(convertir_size_a_mb_final)

# 3. ASEGURAR TIPO NUMÉRICO (Esto evita el error de median())
df_final['Size'] = pd.to_numeric(df_final['Size'], errors='coerce')

# 4. IMPUTACIÓN TÉCNICA (Punto 5 de la pauta: Transformaciones)
# Calculamos la mediana de los tamaños conocidos
mediana_size = df_final['Size'].median()

# Rellenamos los "Varies with device" (que ahora son NaN) con la mediana
df_final['Size'] = df_final['Size'].fillna(mediana_size)

print(f"✅ Transformación exitosa.")
print(f"✅ Mediana aplicada: {mediana_size:.2f} MB")
print(f"✅ Nulos restantes en Size: {df_final['Size'].isnull().sum()}")

# Mostrar las primeras filas para verificar
display(df_final[['App', 'Size']].head())

✅ Transformación exitosa.
✅ Mediana aplicada: 13.00 MB
✅ Nulos restantes en Size: 0

                                                 App  Size
0     Photo Editor & Candy Camera & Grid & ScrapBook  19.0
1                                Coloring book moana  14.0
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   8.7
3                              Sketch - Draw & Paint  25.0
4              Pixel Draw - Number Art Coloring Book   2.8

Paso 10: Creación de métricas comparativas (Popularidad Relativa)
En este paso, el código deja de limpiar y empieza a generar valor. El objetivo es crear una nueva columna que nos diga qué tan exitosa es una aplicación comparada únicamente con otras de su mismo tipo (nicho).

Código: Primero, calcula el promedio de descargas para cada categoría (ej. cuánto se descarga en promedio una app de "Juegos"). Luego, divide las instalaciones de cada app individual entre ese promedio para obtener la Popularidad Relativa.

In [19]:
# Cálculo del promedio de instalaciones por categoría
stats_categoria = df_final.groupby('Category')['Installs'].transform('mean')

# Transformación Avanzada: Popularidad Relativa (Vectorización pura)
# Indica cuántas veces más (o menos) se instala una app respecto al promedio de su nicho
df_final['Relative_Popularity'] = np.divide(df_final['Installs'], stats_categoria)

print("✅ Nueva métrica 'Relative_Popularity' creada mediante Broadcasting.")

✅ Nueva métrica 'Relative_Popularity' creada mediante Broadcasting.

Paso 11: Normalización de formatos económicos y temporales
En este paso, el código prepara los datos para análisis financieros y de actualidad. El objetivo es convertir información que está guardada como "texto" en valores que Python pueda entender para hacer cálculos de dinero y organizar eventos en el tiempo.

Código: Primero, localiza la columna de Price, elimina el símbolo de "$" y transforma el valor a un número decimal (float), permitiendo así sumar ingresos o calcular promedios de costos. Segundo, toma la columna Last Updated y la convierte a un formato de fecha especial (datetime), lo que permite saber con exactitud cuánto tiempo ha pasado desde la última actualización de cada aplicación.

In [24]:
# Eliminamos el signo '$' de la columna Price
df_final['Price'] = df_final['Price'].apply(lambda x: str(x).replace('$', '') if '$' in str(x) else str(x))

# Convertimos la columna a tipo flotante (float)
df_final['Price'] = df_final['Price'].astype(float)

In [23]:
# Convertimos la columna Last Updated a formato datetime de pandas
df_final['Last Updated'] = pd.to_datetime(df_final['Last Updated'])

Paso 12: Optimización de memoria y auditoría técnica final
En este último paso, el código realiza un ajuste de "tuercas" para que el archivo sea más ligero y rápido de procesar, terminando con una validación total de que los datos están listos para ser exportados o analizados.

Código: Selecciona las columnas que contienen etiquetas repetitivas (como "Category" o "Type") y cambia su formato interno de "texto común" a uno especial llamado category. Finalmente, vuelve a imprimir el reporte de integridad para asegurar que, tras todas las transformaciones, el dataset sigue estando libre de errores.

In [25]:
cols_a_categorizar = ['Category', 'Type', 'Content Rating', 'Genres']
for col in cols_a_categorizar:
    df_final[col] = df_final[col].astype('category')

print("✅ Optimización de memoria completada: Columnas convertidas a 'category'.")
print(df_final.info())
print(df_final.head())

# Ejecutar validación
estado = validar_estado_final(df_final)
print("\n--- Reporte de Integridad Final ---")
for k, v in estado.items():
    print(f"{k}: {v}")

✅ Optimización de memoria completada: Columnas convertidas a 'category'.
<class 'pandas.core.frame.DataFrame'>
Index: 10357 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   App                  10357 non-null  object
 1   Category             10357 non-null  category
 2   Rating               10357 non-null  float64
 3   Reviews              10357 non-null  object
 4   Size                 10357 non-null  float64
 5   Installs             10357 non-null  int64
 6   Type                 10357 non-null  category
 7   Price                10357 non-null  float64
 8   Content Rating       10357 non-null  category
 9   Genres               10357 non-null  category
 10  Last Updated         10357 non-null  datetime64[ns]
 11  Current Ver          10357 non-null  object
 12  Android Ver          10357 non-null  object
 13  Relative_Popularity  10357 non-null  float64
dtypes: category(4), datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 937.2+ KB
None
                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                Coloring book moana  ART_AND_DESIGN     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3

  Reviews  Size  Installs  Type  Price Content Rating  \
0     159  19.0     10000  Free    0.0       Everyone
1     967  14.0    500000  Free    0.0       Everyone
2   87510   8.7   5000000  Free    0.0       Everyone
3  215644  25.0  50000000  Free    0.0           Teen
4     967   2.8    100000  Free    0.0       Everyone

                      Genres Last Updated         Current Ver   Android Ver  \
0               Art & Design   2018-01-07               1.0.0  4.0.3 and up
1  Art & Design;Pretend Play   2018-01-15               2.0.0  4.0.3 and up
2               Art & Design   2018-08-01               1.2.4  4.0.3 and up
3               Art & Design   2018-06-08  Varies with device    4.2 and up
4    Art & Design;Creativity   2018-06-20                 1.1    4.4 and up

   Relative_Popularity
0             0.005228
1             0.261384
2             2.613841
3            26.138408
4             0.052277

--- Reporte de Integridad Final ---
Nulos totales: 0
Duplicados totales: 0
Dimensiones finales: (10357, 14)

Paso 13: Exportación y entrega de resultados
En este paso, el código toma todo el trabajo realizado en la memoria de la computadora y lo guarda en un archivo físico (CSV) que puedes abrir en Excel, Power BI o compartir con otras personas.

Código: Se define el nombre del archivo de salida y se utiliza la función .to_csv() para guardar la tabla. Se configuran dos detalles técnicos importantes: index=False para no añadir columnas de números innecesarias y encoding='utf-8-sig' para que los acentos y símbolos se lean correctamente en cualquier programa.

In [26]:
# Definir el nombre del archivo de salida
Google_Play_Store_Apps_Limpio = "googleplaystore_limpio.csv"

try:
    # Exportar el DataFrame procesado
    # index=False evita que se cree una columna extra con los números de fila
    # encoding='utf-8-sig' asegura que los caracteres especiales se vean bien en Excel
    df_final.to_csv(Google_Play_Store_Apps_Limpio, index=False, encoding='utf-8-sig')

    print(f"✅ Archivo exportado exitosamente como: {Google_Play_Store_Apps_Limpio}")
    print(f"Dimensiones finales guardadas: {df_final.shape}")

except Exception as e:
    print(f"❌ Error al guardar el archivo: {e}")

✅ Archivo exportado exitosamente como: googleplaystore_limpio.csv
Dimensiones finales guardadas: (10357, 14)

Paso 14: Descarga local del archivo procesado
Este paso es el puente final entre el servidor en la nube y tu propia computadora.

Código: Utiliza la librería especial de Google Colab (from google.colab import files) para activar una instrucción de descarga directa en el navegador.

In [28]:
from google.colab import files

files.download(Google_Play_Store_Apps_Limpio)